### ISSUE TITLE
Does not work on Androıd 6.0 Marshmellow 

### ISSUE THREAD

**Issue by iballan** [marshallino16/FloatingView#6] opened 2015-11-16 11:46 UTC
I tried to run it on Marshmellow it did not work. It crashes as soon as the view will show up

**Comment by marshallino16** [comment] 2015-11-17 09:59
Post your stack trace please.

**Comment by amaydiam** [comment] 2015-11-22 13:29
`FATAL EXCEPTION: main
                                                                                  Process: fr.anthonyfernandez.floatingmenu, PID: 23938
                                                                                  java.lang.RuntimeException: Unable to create service fr.anthonyfernandez.floatingmenu.Service.ServiceFloating: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@4a5d000 -- permission denied for this window type
                                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
                                                                                      at android.app.ActivityThread.-wrap4(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                   Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@4a5d000 -- permission denied for this window type
                                                                                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
                                                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                                      at fr.anthonyfernandez.floatingmenu.Service.ServiceFloating.onCreate(ServiceFloating.java:102)
                                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
                                                                                      at android.app.ActivityThread.-wrap4(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by amaydiam** [comment] 2015-11-22 13:29
permision denied

**Comment by iballan** [comment] 2015-11-23 08:14
I guess this is the problem:
[Settings.canDrawOverlays](http://developer.android.com/reference/android/provider/Settings.html#canDrawOverlays(android.content.Context))

> As of API level 23, an app cannot draw on top of other apps unless it declares the SYSTEM_ALERT_WINDOW permission in its manifest, and the user specifically grants the app this capability. To prompt the user to grant this approval, the app must send an intent with the action ACTION_MANAGE_OVERLAY_PERMISSION, which causes the system to display a permission management screen

As i understood that we cant draw over other apps anymore. For API 23, User should grant the app permission in order to allow the app to draw over other apps!!

**Comment by marshallino16** [comment] 2015-11-23 09:04
Yes, it is due to marshmallow's permissions system, check this out : http://developer.android.com/training/permissions/requesting.html

**Comment by iballan** [comment] 2015-11-23 09:15
There are now 3 groups of permissions:
1- Normal Permissions
2- Dangerous Permissions
**3- Special Permissions**

They said:
> most apps should not use them.

and 

>If an app needs one of these permissions, it must declare the permission in the manifest, and send an intent requesting the user's authorization. The system responds to the intent by showing a detailed management screen to the user.

[Permissions normal-dengerous](http://developer.android.com/guide/topics/security/permissions.html#normal-dangerous)

**Comment by marshallino16** [comment] 2015-11-23 10:04
thanks to @amaydiam, fixed with [Pull request 7](https://github.com/marshallino16/FloatingView/pull/7)

**Closed by marshallino16** 2015-11-23 10:04 UTC
